apiVersion: v1
data:
  apiToken: ZHQwYzAxLjUySEpINFk3SkVHS0NQTVlNSlVCRFRWQS5ZWVFHUUVKSk5WQTVTNFVITVdaRzZONkZNVjI1NlNMSzVBQTUyUEJDMzVRQkxFSE5BT0ZBVVdRRE1XTURSTlA0
  dataIngestToken: ZHQwYzAxLlZRV0w0T1JOMlIyRTVJT1JHQVg1VEpYRS5BWExDWkM1SFRONkFNTDNWUzdVNUw1UEdZTFdIUlA1MkxLQ05XTTdCWjJJNEhCTExBSTJLNU1DUkE3Q1JEMlFF
kind: Secret
metadata:
  name: vogler-boutique-fs
  namespace: dynatrace
type: Opaque
---
apiVersion: dynatrace.com/v1beta3
kind: DynaKube
metadata:
  name: vogler-boutique-fs
  namespace: dynatrace
  annotations:
    feature.dynatrace.com/k8s-app-enabled: "true"
# Link to api reference for further information: https://docs.dynatrace.com/docs/ingest-from/setup-on-k8s/reference/dynakube-parameters
spec:
  apiUrl: https://wsf67781.sprint.dynatracelabs.com/api
  metadataEnrichment:
    enabled: true
  oneAgent:
    cloudNativeFullStack:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
          operator: Exists
  activeGate:
    capabilities:
      - routing
      - kubernetes-monitoring
    resources:
      requests:
        cpu: 500m
        memory: 1.5Gi
      limits:
        cpu: 1000m
        memory: 1.5Gi
  templates:
    extensionExecutionController:
      imageRef:
        repository: wsf67781.sprint.dynatracelabs.com/linux/dynatrace-eec
        tag: latest
  extensions: {}
  logMonitoring: {}
